# Site settings
title: "Patryk Jakub Nowak Resume"
description: "My Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Patryk Jakub Nowak"
resume_title:                   "Backend Developer"
resume_contact_email:           "patryk_nowak@yahoo.pl"
resume_contact_telephone:       "+48 570 012 280"
resume_contact_address:         "Niepodleglosci 97a, Wieliszew, POLAND"
resume_header_contact_info: "Niepodleglosci 97a, Wieliszew, POLAND | +48 570 012 280 | patryk_nowak@yahoo.pl"
resume_header_intro: "<p>I'm Backend Developer, that strives to develop efficient, beautiful and readable code, but also to get things done. I'm working 100% remotely.</p>

                        <p>I' working using:</p>
                      <ul>
                        <li>PHP</li>
                        <li>Symfony</li>
                        <li>Python</li>
                      </ul>

                        <p>Also I know well:</p>
                      <ul>
                        <li>Elixir</li>
                        <li>Phoenix framework</li>
                      </ul>

                        <p>Yet I could code also in:</p>
                      <ul>
                        <li>Ruby</li>
                        <li>Rails</li>
                        <li>Javascript</li>
                        <li>Express</li>
                      </ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/patnowak"
  resume_stackoverflow_url:     "https://stackoverflow.com/users/3741729/patnowak"
  resume_linkedin_url:          "https://www.linkedin.com/in/patryk-nowak-b487a7b2"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
